# XCA 데이터셋 - ColdDiff 학습 설정
model:
  arch_name: colddiff
  image_size: 320
  dim: 32
  channel_mult: [1, 2, 3, 4]
  timesteps: 50
  loss_type: mse
  learning_rate: 0.0002
  weight_decay: 0.00001
  experiment_name: colddiff
  data_name: xca
  conditioning_fmap_size: 224
  num_ensemble: 1
  use_ema: true
  ema_decay: 0.9999
  log_image_enabled: false
  log_image_names:
    - '0000.png'
    - '0010.png'
    - '0019.png'

data:
  name: xca
  train_dir: data/xca_full/train
  val_dir: data/xca_full/val
  test_dir: data/xca_full/test
  crop_size: 320
  train_bs: 6
  num_samples_per_image: 16

trainer:
  max_epochs: 500
  accelerator: gpu
  devices: 1
  precision: 32-true
  enable_progress_bar: true
  check_val_every_n_epoch: 25
  accumulate_grad_batches: 8
  log_every_n_steps: 10
  gradient_clip_val: 1.0
