# ROSSA 데이터셋 - SegDiff 학습 설정
model:
  arch_name: segdiff
  image_size: 224
  dim: 32
  timesteps: 50
  learning_rate: 0.0002
  weight_decay: 0.00001
  experiment_name: segdiff
  data_name: rossa
  num_ensemble: 1
  use_ema: true
  ema_decay: 0.9999
  log_image_enabled: false
  log_image_names:
    - '201.png'
    - '205.png'
    - '210.png'
  loss_type: mse

data:
  name: rossa
  train_manual_dir: data/ROSSA/train_manual
  train_sam_dir: data/ROSSA/train_sam
  val_dir: data/ROSSA/val
  test_dir: data/ROSSA/test
  crop_size: 224
  train_bs: 6
  use_sam: false  # true: SAM-annotated 데이터 포함
  num_samples_per_image: 16
trainer:
  max_epochs: 500
  accelerator: gpu
  devices: 1
  precision: 32-true
  enable_progress_bar: true
  check_val_every_n_epoch: 25
  accumulate_grad_batches: 8
  log_every_n_steps: 10
  gradient_clip_val: 1.0
