# OCTA500 6M 데이터셋 - CSNet 학습 설정
model:
  arch_name: csnet
  in_channels: 1
  num_classes: 2
  image_size: 224
  learning_rate: 0.0002
  weight_decay: 0.00001
  log_image_enabled: true
  log_image_names:
    - '10181.bmp'
    - '10185.bmp'
    - '10190.bmp'

data:
  name: octa500_6m
  train_dir: data/OCTA500_6M/train
  val_dir: data/OCTA500_6M/val
  test_dir: data/OCTA500_6M/test
  crop_size: 224
  train_bs: 6
  num_workers: 8
  num_samples_per_image: 16

trainer:
  max_epochs: 400
  accelerator: gpu
  devices: 1
  precision: 32-true
  log_every_n_steps: 10
  check_val_every_n_epoch: 25
  gradient_clip_val: 1.0
