# OCTA500 6M dataset - SegDiff training config
model:
  arch_name: segdiff
  image_size: 224
  dim: 32
  timesteps: 50
  learning_rate: 0.0002
  weight_decay: 0.00001
  experiment_name: segdiff
  data_name: octa500_6m
  num_ensemble: 1
  use_ema: true
  ema_decay: 0.9999
  log_image_enabled: false
  log_image_names:
    - '10181.bmp'
    - '10185.bmp'
    - '10190.bmp'
  loss_type: mse

data:
  name: octa500_6m
  train_dir: data/OCTA500_6M/train
  val_dir: data/OCTA500_6M/val
  test_dir: data/OCTA500_6M/test
  crop_size: 224
  train_bs: 6
  num_workers: 8
  num_samples_per_image: 16

trainer:
  max_epochs: 500
  accelerator: gpu
  devices: 1
  precision: 32-true  # Diffusion needs FP32
  enable_progress_bar: false
  check_val_every_n_epoch: 25
  accumulate_grad_batches: 8
  gradient_clip_val: 1.0
